import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e4e1ee",
        primary: "#c3c0ff",
        tertiary: "#ffb690",
        secondary: "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "on-tertiary-container": "#ffd2bd",
        "tertiary-container": "#a04500",
        "on-tertiary": "#552100",
        "inverse-primary": "#4d44e3",
        "on-secondary": "#003640",
        "surface-dim": "#13121b",
        "surface-container-lowest": "#0e0d16",
        "error-container": "#93000a",
        "outline-variant": "#464555",
        "secondary-fixed": "#acedff",
        outline: "#918fa1",
        "surface-variant": "#35343e",
        "on-tertiary-fixed": "#341100",
        "surface-tint": "#c3c0ff",
        "on-primary": "#1d00a5",
        "secondary-container": "#03b5d3",
        "tertiary-fixed-dim": "#ffb690",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "on-secondary-container": "#00424e",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#783200",
        "on-background": "#e4e1ee",
        "surface-container": "#1f1f28",
        surface: "#13121b",
        "on-secondary-fixed-variant": "#004e5c",
        "primary-container": "#4f46e5",
        "secondary-fixed-dim": "#4cd7f6",
        "inverse-on-surface": "#302f39",
        background: "#13121b",
        "on-surface-variant": "#c7c4d8",
        "on-error": "#690005",
        "surface-container-low": "#1b1b24",
        "surface-container-high": "#2a2933",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed": "#ffdbca",
        "primary-fixed": "#e2dfff",
        error: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xxl: "5rem",
        xs: "0.5rem",
        gutter: "24px",
        md: "1.5rem",
        sm: "1rem",
        margin: "32px",
        lg: "2rem",
        xl: "3rem",
        base: "4px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "display-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.3", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
